let data =[{'genre': 'Fiction',
  'books': [{'title': 'The Great Gatsby',
    'author': 'David Davis',
    'year': 1950},
   {'title': 'To Kill a Mockingbird', 'author': 'Alex Wilson', 'year': 2023},
   {'title': 'Pride and Prejudice', 'author': 'Sarah Johnson', 'year': 2003},
   {'title': 'The Catcher in the Rye', 'author': 'Jane Wilson', 'year': 1954},
   {'title': 'The Kite Runner', 'author': 'Alex Brown', 'year': 2010},
   {'title': 'Little Fires Everywhere',
    'author': 'David Johnson',
    'year': 1953},
   {'title': 'The Night Circus', 'author': 'Michael Wilson', 'year': 1983},
   {'title': 'Normal People', 'author': 'Jane Brown', 'year': 2003}]},
 {'genre': 'Non-Fiction',
  'books': [{'title': 'Sapiens', 'author': 'David Wilson', 'year': 2012},
   {'title': 'Educated', 'author': 'Sarah Brown', 'year': 1970},
   {'title': 'Becoming', 'author': 'John Brown', 'year': 2005},
   {'title': 'The Wright Brothers', 'author': 'Michael Smith', 'year': 2018},
   {'title': 'Into the Wild', 'author': 'Jane Johnson', 'year': 1989},
   {'title': 'Born a Crime', 'author': 'Sarah Wilson', 'year': 2015},
   {'title': 'The Immortal Life of Henrietta Lacks',
    'author': 'Sarah Wilson',
    'year': 1958}]},
 {'genre': 'Science Fiction',
  'books': [{'title': 'Dune', 'author': 'Alex Wilson', 'year': 2013},
   {'title': "Ender's Game", 'author': 'Emily Johnson', 'year': 2021},
   {'title': 'Neuromancer', 'author': 'John Johnson', 'year': 1993},
   {'title': 'Snow Crash', 'author': 'Jane Brown', 'year': 1955},
   {'title': 'The Martian', 'author': 'Jane Johnson', 'year': 2006},
   {'title': 'Ready Player One', 'author': 'Michael Wilson', 'year': 1984},
   {'title': 'Hyperion', 'author': 'Michael Davis', 'year': 2018},
   {'title': 'Foundation', 'author': 'Michael Johnson', 'year': 2023}]},
 {'genre': 'Fantasy',
  'books': [{'title': "Harry Potter and the Sorcerer's Stone",
    'author': 'Alex Brown',
    'year': 2005},
   {'title': 'The Hobbit', 'author': 'Sarah Johnson', 'year': 1988},
   {'title': 'The Name of the Wind', 'author': 'David Wilson', 'year': 1981},
   {'title': 'Mistborn', 'author': 'Michael Brown', 'year': 1974},
   {'title': 'A Game of Thrones', 'author': 'Jane Brown', 'year': 1997},
   {'title': 'Eragon', 'author': 'Sarah Johnson', 'year': 1980},
   {'title': 'The Way of Kings', 'author': 'Emily Brown', 'year': 1976}]},
 {'genre': 'Mystery',
  'books': [{'title': 'Gone Girl', 'author': 'Emily Johnson', 'year': 1950},
   {'title': 'The Girl with the Dragon Tattoo',
    'author': 'Emily Smith',
    'year': 2019},
   {'title': 'The Da Vinci Code', 'author': 'Sarah Davis', 'year': 1984},
   {'title': 'In the Woods', 'author': 'Michael Wilson', 'year': 1980},
   {'title': 'Big Little Lies', 'author': 'Jane Johnson', 'year': 1994},
   {'title': 'The Silent Patient', 'author': 'Sarah Wilson', 'year': 2013},
   {'title': 'The Reversal', 'author': 'Alex Wilson', 'year': 1971}]},
 {'genre': 'Thriller',
  'books': [{'title': 'The Girl on the Train',
    'author': 'John Johnson',
    'year': 2006},
   {'title': 'Before I Go to Sleep', 'author': 'John Brown', 'year': 1951},
   {'title': 'Behind Closed Doors', 'author': 'Emily Brown', 'year': 1990},
   {'title': 'The Couple Next Door', 'author': 'John Brown', 'year': 1997},
   {'title': 'The Woman in Cabin 10', 'author': 'Emily Smith', 'year': 1950},
   {'title': 'I Am Watching You', 'author': 'Alex Smith', 'year': 1976}]},
 {'genre': 'Romance',
  'books': [{'title': 'Pride and Prejudice',
    'author': 'Sarah Davis',
    'year': 1973},
   {'title': 'The Notebook', 'author': 'Emily Wilson', 'year': 1953},
   {'title': 'Me Before You', 'author': 'John Smith', 'year': 1989},
   {'title': 'Outlander', 'author': 'Sarah Davis', 'year': 1960},
   {'title': 'The Hating Game', 'author': 'Alex Davis', 'year': 1958},
   {'title': 'It Ends With Us', 'author': 'Sarah Wilson', 'year': 2006},
   {'title': 'Beach Read', 'author': 'John Brown', 'year': 2012}]},
 {'genre': 'Horror',
  'books': [{'title': 'The Shining', 'author': 'Jane Davis', 'year': 1982},
   {'title': 'It', 'author': 'Michael Smith', 'year': 2018},
   {'title': 'Dracula', 'author': 'David Johnson', 'year': 1955},
   {'title': 'Bird Box', 'author': 'Michael Brown', 'year': 1982},
   {'title': 'The Haunting of Hill House',
    'author': 'Sarah Wilson',
    'year': 1974},
   {'title': 'Mexican Gothic', 'author': 'Alex Davis', 'year': 2009},
   {'title': 'House of Leaves', 'author': 'David Brown', 'year': 1993}]},
 {'genre': 'Historical Fiction',
  'books': [{'title': 'All the Light We Cannot See',
    'author': 'John Smith',
    'year': 1967},
   {'title': 'The Book Thief', 'author': 'Jane Brown', 'year': 1959},
   {'title': 'The Help', 'author': 'Alex Johnson', 'year': 2020},
   {'title': 'The Nightingale', 'author': 'David Davis', 'year': 2014},
   {'title': 'A Thousand Splendid Suns',
    'author': 'Emily Wilson',
    'year': 2004},
   {'title': 'The Tattooist of Auschwitz',
    'author': 'Michael Johnson',
    'year': 1983}]},
 {'genre': 'Biography / Autobiography',
  'books': [{'title': 'Steve Jobs', 'author': 'John Brown', 'year': 1956},
   {'title': 'Long Walk to Freedom', 'author': 'Jane Wilson', 'year': 1973},
   {'title': 'The Diary of a Young Girl',
    'author': 'Alex Brown',
    'year': 1981},
   {'title': 'I Am Malala', 'author': 'Michael Smith', 'year': 1953},
   {'title': 'When Breath Becomes Air',
    'author': 'Michael Johnson',
    'year': 1998},
   {'title': 'Bossypants', 'author': 'Jane Wilson', 'year': 1979},
   {'title': 'Open', 'author': 'Jane Brown', 'year': 2000}]},
 {'genre': 'Self-Help',
  'books': [{'title': 'The 7 Habits of Highly Effective People',
    'author': 'David Brown',
    'year': 2016},
   {'title': 'Atomic Habits', 'author': 'Jane Wilson', 'year': 1989},
   {'title': 'How to Win Friends and Influence People',
    'author': 'Emily Davis',
    'year': 1965},
   {'title': 'Think and Grow Rich', 'author': 'John Smith', 'year': 1985},
   {'title': 'The Subtle Art of Not Giving a F*ck',
    'author': 'David Johnson',
    'year': 1961},
   {'title': 'You Are a Badass', 'author': 'Michael Brown', 'year': 1952}]},
 {'genre': 'Poetry',
  'books': [{'title': 'Milk and Honey', 'author': 'Alex Wilson', 'year': 1990},
   {'title': 'The Sun and Her Flowers',
    'author': 'David Johnson',
    'year': 2017},
   {'title': 'Leaves of Grass', 'author': 'Emily Smith', 'year': 2023},
   {'title': 'The Raven and Other Poems',
    'author': 'Jane Wilson',
    'year': 1988},
   {'title': 'Ariel', 'author': 'David Johnson', 'year': 1950},
   {'title': 'The Waste Land', 'author': 'Michael Brown', 'year': 2003}]},
 {'genre': 'Graphic Novels / Comics',
  'books': [{'title': 'Watchmen', 'author': 'Sarah Smith', 'year': 2017},
   {'title': 'Maus', 'author': 'Jane Johnson', 'year': 1998},
   {'title': 'V for Vendetta', 'author': 'John Johnson', 'year': 1970},
   {'title': 'Batman: The Killing Joke',
    'author': 'Michael Smith',
    'year': 1980},
   {'title': 'Saga', 'author': 'Alex Davis', 'year': 2007},
   {'title': 'Persepolis', 'author': 'Sarah Johnson', 'year': 2004},
   {'title': 'Scott Pilgrim', 'author': 'Alex Davis', 'year': 1984}]},
 {'genre': 'Adventure',
  'books': [{'title': 'Life of Pi', 'author': 'Emily Davis', 'year': 2013},
   {'title': 'Treasure Island', 'author': 'Jane Davis', 'year': 2014},
   {'title': 'The Call of the Wild', 'author': 'Sarah Johnson', 'year': 2022},
   {'title': 'The Alchemist', 'author': 'Alex Brown', 'year': 2013},
   {'title': 'Hatchet', 'author': 'Emily Wilson', 'year': 1996},
   {'title': 'The Lost City of Z', 'author': 'Sarah Smith', 'year': 1951}]},
 {'genre': 'Drama',
  'books': [{'title': 'Death of a Salesman',
    'author': 'Jane Johnson',
    'year': 1964},
   {'title': 'A Streetcar Named Desire',
    'author': 'Jane Johnson',
    'year': 1967},
   {'title': 'Hamlet', 'author': 'Michael Smith', 'year': 2016},
   {'title': 'Long Day’s Journey Into Night',
    'author': 'David Wilson',
    'year': 1996},
   {'title': 'The Glass Menagerie', 'author': 'Jane Brown', 'year': 2022},
   {'title': 'Fences', 'author': 'Alex Johnson', 'year': 2011}]},
 {'genre': 'Young Adult (YA)',
  'books': [{'title': 'The Fault in Our Stars',
    'author': 'Jane Wilson',
    'year': 1994},
   {'title': 'Divergent', 'author': 'Jane Brown', 'year': 1959},
   {'title': 'The Hunger Games', 'author': 'Alex Johnson', 'year': 1965},
   {'title': 'Twilight', 'author': 'John Brown', 'year': 1991},
   {'title': 'Eleanor & Park', 'author': 'Jane Davis', 'year': 1979},
   {'title': 'Paper Towns', 'author': 'Jane Brown', 'year': 1992},
   {'title': 'Looking for Alaska', 'author': 'Alex Smith', 'year': 2009}]},
 {'genre': "Children's Books",
  'books': [{'title': "Charlotte's Web",
    'author': 'Emily Wilson',
    'year': 2010},
   {'title': 'Where the Wild Things Are',
    'author': 'David Brown',
    'year': 1968},
   {'title': 'Matilda', 'author': 'John Smith', 'year': 1980},
   {'title': 'The Cat in the Hat', 'author': 'David Wilson', 'year': 1983},
   {'title': 'The Gruffalo', 'author': 'John Johnson', 'year': 1969},
   {'title': 'Green Eggs and Ham', 'author': 'Jane Smith', 'year': 1960}]},
 {'genre': 'Classics',
  'books': [{'title': '1984', 'author': 'Emily Davis', 'year': 1954},
   {'title': 'Moby-Dick', 'author': 'Jane Smith', 'year': 2016},
   {'title': 'Jane Eyre', 'author': 'Alex Johnson', 'year': 1965},
   {'title': 'Wuthering Heights', 'author': 'Alex Johnson', 'year': 1973},
   {'title': 'Great Expectations', 'author': 'Alex Johnson', 'year': 1963},
   {'title': 'Crime and Punishment', 'author': 'Emily Brown', 'year': 2017},
   {'title': 'Brave New World', 'author': 'David Wilson', 'year': 1967}]},
 {'genre': 'Spiritual / Religious',
  'books': [{'title': 'The Bible', 'author': 'Jane Davis', 'year': 2004},
   {'title': 'The Bhagavad Gita', 'author': 'David Wilson', 'year': 1952},
   {'title': 'The Quran', 'author': 'John Johnson', 'year': 1977},
   {'title': 'The Tao Te Ching', 'author': 'Sarah Smith', 'year': 1979},
   {'title': 'The Power of Now', 'author': 'Jane Johnson', 'year': 1967},
   {'title': 'The Purpose Driven Life',
    'author': 'Jane Johnson',
    'year': 2013}]},
 {'genre': 'Science & Technology',
  'books': [{'title': 'A Brief History of Time',
    'author': 'Alex Brown',
    'year': 1976},
   {'title': 'Cosmos', 'author': 'David Davis', 'year': 1951},
   {'title': 'The Gene', 'author': 'Michael Johnson', 'year': 1952},
   {'title': 'Astrophysics for People in a Hurry',
    'author': 'John Brown',
    'year': 1956},
   {'title': 'The Innovators', 'author': 'John Johnson', 'year': 2000},
   {'title': 'Homo Deus', 'author': 'Michael Smith', 'year': 1980},
   {'title': 'The Singularity Is Near',
    'author': 'Sarah Davis',
    'year': 1966}]}]

export default data;